(after! org
        (setq org-emphasis-alist
         '(("*" (bold))
           ("/" italic)
           ("_" underline)
           ("=" redd)
           ("~" (:background "deep sky blue" :foreground "MidnightBlue"))
           ("+" (:strike-through t))))
  (setq org-ellipsis " ▾ ")
  (appendq! +ligatures-extra-symbols
          `(:checkbox      "☐"
            :pending       "◼"
            :checkedbox    "☑"
            :list_property "∷"
            :em_dash       "—"
            :ellipses      "…"
            :arrow_right   "→"
            :arrow_left    "←"
            :title         "𝙏"
            :subtitle      "𝙩"
            :author        "𝘼"
            :date          "𝘿"
            :property      "☸"
            :options       "⌥"
            :startup       "⏻"
            :setupfile     "⚝"
            :macro         "𝓜"
            :macro         "🄼"
            :html_head     "🅷"
            :html          "🅗"
            :latex_class   "🄻"
            :latex_header  "🅻"
            :beamer_header "🅑"
            :latex         "🅛"
            :attr_latex    "🄛"
            :attr_html     "🄗"
            :attr_org      "⒪"
            :bibliography  "🕮"
            :print_bib     "🖶"
            :begin_quote   "❝"
            :end_quote     "❞"
            :caption       "☰"
            :header        "›"
            :results       "🠶"
            :begin_export  "⏩"
            :end_export    "⏪"
            :name          "»"
            :src_block     "»"
            :src_block_end "«"
            :properties    "⚙"
            :end           "∎"
            :priority_a   ,(propertize "⚑" 'face 'all-the-icons-red)
            :priority_b   ,(propertize "⬆" 'face 'all-the-icons-orange)
            :priority_c   ,(propertize "■" 'face 'all-the-icons-yellow)
            :priority_d   ,(propertize "⬇" 'face 'all-the-icons-green)
            :priority_e   ,(propertize "❓" 'face 'all-the-icons-blue)))
  (set-ligatures! 'org-mode :merge t
    :checkbox      "[ ]"
    :pending       "[-]"
    :checkedbox    "[X]"
    :list_property "::"
    :em_dash       "---"
    :ellipsis      "..."
    :arrow_right   "->"
    :arrow_left    "<-"
    :title         "#+TITLE:"
    :subtitle      "#+SUBTITLE:"
    :author        "#+AUTHOR:"
    :date          "#+DATE:"
    :property      "#+PROPERTY:"
    :options       "#+OPTIONS:"
    :setupfile     "#+SETUPFILE:"
    :startup       "#+STARTUP:"
    :macro         "#+MACRO:"
    :html_head     "#+HTML_HEAD:"
    :html          "#+HTML:"
    :latex_class   "#+LATEX_CLASS:"
    :latex_header  "#+LATEX_HEADER:"
    :bibliography  "#+BIBLIOGRAPHY:"
    :print_bib     "#+PRINT_BIBLIOGRAPHY:"
    :beamer_header "#+BEAMER_HEADER:"
    :latex         "#+LATEX:"
    :attr_latex    "#+ATTR_LATEX:"
    :attr_html     "#+ATTR_HTML:"
    :attr_org      "#+ATTR_ORG:"
    :begin_quote   "#+BEGIN_QUOTE"
    :end_quote     "#+END_QUOTE"
    :src-block     "#+BEGIN_SRC"
    :src-block_end "#+END_SRC"
    :caption       "#+CAPTION:"
    :header        "#+HEADER:"
    :begin_export  "#+BEGIN_EXPORT"
    :end_export    "#+END_EXPORT"
    :results       "#+RESULTS:"
    :property      ":PROPERTIES:"
    :end           ":END:"
    :priority_a    "[#A]"
    :priority_b    "[#B]"
    :priority_c    "[#C]"
    :priority_d    "[#D]"
)
  (plist-put +ligatures-extra-symbols :name "⁍"))
